Repository BlueQuartzSoftware/SIMPL, pull requests merged in 2018-12, with the labels that each got.

#272 Address VerifyPreconditions const change in ITK 5 master
  Source/SIMPLib/ITK/itkDream3DITransformContainerToTransform.h
  Source/SIMPLib/ITK/itkDream3DITransformContainerToTransform.hxx
  Source/SIMPLib/ITK/itkDream3DTransformContainerToTransform.h
  Source/SIMPLib/ITK/itkDream3DTransformContainerToTransform.hxx
  Source/SIMPLib/ITK/itkInPlaceDream3DDataToImageFilter.h
  Source/SIMPLib/ITK/itkInPlaceDream3DDataToImageFilter.hxx
  Source/SIMPLib/ITK/itkInPlaceImageToDream3DDataFilter.h
  Source/SIMPLib/ITK/itkInPlaceImageToDream3DDataFilter.hxx
Labels: enhancement

#273 Apply clang-tidy modernize and readability fixes to DataArray class.
  Source/SIMPLib/DataArrays/DataArray.hpp
Labels: enhancement

#274 Update DataContainer and DataContainerArray to modern C++ standards
  Source/SIMPLib/DataContainers/DataContainer.cpp
  Source/SIMPLib/DataContainers/DataContainer.h
  Source/SIMPLib/DataContainers/DataContainerArray.cpp
  Source/SIMPLib/DataContainers/DataContainerArray.h
Labels: enhancement

#275 Cleanup the IconPushButton styles and remove API to get the PushButton CSS
  Resources/SIMPL.qrc
  Resources/SIMPL/icons/images/arrow_down.png
  Resources/SIMPL/icons/images/arrow_down@2x.png
  Resources/SIMPL/icons/images/arrow_down_green.png
  Resources/SIMPL/icons/images/arrow_down_green@2x.png
  Resources/SIMPL/icons/images/arrow_left.png
  Resources/SIMPL/icons/images/arrow_left@2x.png
  Resources/SIMPL/icons/images/arrow_left_green.png
  Resources/SIMPL/icons/images/arrow_left_green@2x.png
  Resources/SIMPL/icons/images/arrow_right.png
  Resources/SIMPL/icons/images/arrow_right@2x.png
  Resources/SIMPL/icons/images/arrow_right_black.png
  Resources/SIMPL/icons/images/arrow_right_black@2x.png
  Resources/SIMPL/icons/images/arrow_right_green.png
  Resources/SIMPL/icons/images/arrow_right_green@2x.png
  Resources/SIMPL/icons/images/arrow_up.png
  Resources/SIMPL/icons/images/arrow_up@2x.png
  Resources/SIMPL/icons/images/arrow_up_green.png
  Resources/SIMPL/icons/images/arrow_up_green@2x.png
  Resources/SIMPL/icons/svg/arrow-circle-left.svg
  Resources/SIMPL/icons/svg/arrow-circle-right.svg
  Resources/SIMPL/icons/svg/arrow_down.svg
  Resources/SIMPL/icons/svg/arrow_down_green.svg
  Resources/SIMPL/icons/svg/arrow_left.svg
  Resources/SIMPL/icons/svg/arrow_left_green.svg
  Resources/SIMPL/icons/svg/arrow_right.svg
  Resources/SIMPL/icons/svg/arrow_right_black.svg
  Resources/SIMPL/icons/svg/arrow_right_green.svg
  Resources/SIMPL/icons/svg/arrow_up.svg
  Resources/SIMPL/icons/svg/arrow_up_green.svg
  Source/SVWidgetsLib/FilterParameterWidgets/ComparisonContainerWidget.cpp
  Source/SVWidgetsLib/FilterParameterWidgets/ComparisonSelectionWidget.cpp
  Source/SVWidgetsLib/FilterParameterWidgets/ComparisonSetWidget.cpp
  Source/SVWidgetsLib/FilterParameterWidgets/DynamicTableWidget.cpp
  Source/SVWidgetsLib/FilterParameterWidgets/UI_Files/MultiAttributeMatrixSelectionWidget.ui
  Source/SVWidgetsLib/FilterParameterWidgets/UI_Files/MultiDataArraySelectionWidget.ui
  Source/SVWidgetsLib/QtSupport/QtSStyles.cpp
  Source/SVWidgetsLib/QtSupport/QtSStyles.h
  Source/SVWidgetsLib/Widgets/FilterInputWidget.cpp
  Source/SVWidgetsLib/Widgets/SVStyle.cpp
  Source/SVWidgetsLib/Widgets/SVStyle.h
Labels: Bug, enhancement

#276 Create Filter to extract a Vertex Geometry from an Image or RectGrid Geometry
  Source/SIMPLib/CoreFilters/ExtractVertexGeometry.cpp
  Source/SIMPLib/CoreFilters/ExtractVertexGeometry.h
  Source/SIMPLib/CoreFilters/SourceList.cmake
  Source/SIMPLib/CoreFilters/Testing/Cxx/ExtractVertexGeometryTest.cpp
  Source/SIMPLib/CoreFilters/Testing/Cxx/SourceList.cmake
  Source/SIMPLib/Documentation/SIMPLibFilters/CoreFilters/ExtractVertexGeometry.md
  Source/SIMPLib/Geometry/VertexGeom.cpp
  Source/SIMPLib/Testing/TestFileLocations.h.in
Labels: Feature Request

#280 Misc style cleanups focusing on better styling inside of darker themes.
  Resources/SIMPL.qrc
  Source/SVWidgetsLib/FilterParameterWidgets/UI_Files/SeparatorWidget.ui
  Source/SVWidgetsLib/QtSupport/UI_Files/QtSStringEdit.ui
  Source/SVWidgetsLib/Widgets/SVPipelineView.cpp
  Source/SVWidgetsLib/Widgets/SVPipelineView.h
  Source/SVWidgetsLib/Widgets/SVStyle.cpp
  Source/SVWidgetsLib/Widgets/SVStyle.h
  Source/SVWidgetsLib/Widgets/UI_Files/FilterListToolboxWidget.ui
  Source/SVWidgetsLib/Widgets/util/AddFilterCommand.cpp
  Source/SVWidgetsLib/Widgets/util/RemoveFilterCommand.cpp
Labels: In Progress

#282 Add enumeration and accessors for Length Units in the IGeometry class.
  Source/SIMPLib/Geometry/IGeometry.cpp
  Source/SIMPLib/Geometry/IGeometry.h
Labels: enhancement

#283 Add method to FilePathGenerator to generate RC filenames for Montage Data sets
  Source/SIMPLib/Utilities/FilePathGenerator.cpp
  Source/SIMPLib/Utilities/FilePathGenerator.h
Labels: Feature Request, enhancement

#284 Update length unit enums, add length units to Geometry descriptions
  Source/SIMPLib/Common/Constants.h
  Source/SIMPLib/Common/SIMPLibSetGetMacros.h
  Source/SIMPLib/DataContainers/DataContainer.cpp
  Source/SIMPLib/Filtering/FilterPipeline.cpp
  Source/SIMPLib/Geometry/EdgeGeom.cpp
  Source/SIMPLib/Geometry/GeometryHelpers.cpp
  Source/SIMPLib/Geometry/GeometryHelpers.h
  Source/SIMPLib/Geometry/HexahedralGeom.cpp
  Source/SIMPLib/Geometry/IGeometry.cpp
  Source/SIMPLib/Geometry/IGeometry.h
  Source/SIMPLib/Geometry/ImageGeom.cpp
  Source/SIMPLib/Geometry/QuadGeom.cpp
  Source/SIMPLib/Geometry/RectGridGeom.cpp
  Source/SIMPLib/Geometry/TetrahedralGeom.cpp
  Source/SIMPLib/Geometry/TriangleGeom.cpp
  Source/SIMPLib/Geometry/VertexGeom.cpp
Labels: enhancement

#287 Fix runtime crashes inside of FilterPipeline and DataArrayPath
  Source/SIMPLib/DataContainers/DataArrayPath.cpp
  Source/SIMPLib/DataContainers/DataArrayPath.h
  Source/SIMPLib/Filtering/FilterPipeline.cpp
  Source/SIMPLib/Filtering/FilterPipeline.h
  Source/SVWidgetsLib/Widgets/util/AddFilterCommand.h
Labels: Bug
